#!/usr/bin/env python3

from tkinter import *

root= Tk()
root.title('OFA-j')
menu = Menu(root)
root.config(menu=menu)
filemenu=Menu(menu)
menu.add_cascade(label='File', menu=filemenu)
filemenu.add_command(label='New')
filemenu.add_command(label='open')
filemenu.add_separator()
filemenu.add_command(label='Exit', command=root.quit)
helpmenu=Menu(menu)
menu.add_cascade(label='Help', menu=helpmenu)
helpmenu.add_command(label='About')
Label(root, text='PASS NO.').grid(row=0) 
Label(root, text='DATE').grid(row=1) 
e1 = Entry(root) 
e2 = Entry(root) 
e1.grid(row=0, column=1) 
e2.grid(row=1, column=1) 
Label(root, text='COMPANNY NAME').grid(row=2) 
Label(root, text='OFFICER NAME').grid(row=3) 
e3 = Entry(root) 
e4 = Entry(root) 
e3.grid(row=2, column=1) 
e4.grid(row=3, column=1) 
Label(root, text='REASON OF MEETING').grid(row=3) 
Label(root, text='IN TIME').grid(row=4) 
e5 = Entry(root) 
e6 = Entry(root) 
e5.grid(row=3, column=1) 
e6.grid(row=4, column=1)
Label(root, text='COMPANNY ADDRESS').grid(row=5) 
Label(root, text='OFFICER DESIG').grid(row=6) 
e7 = Entry(root) 
e8 = Entry(root) 
e7.grid(row=5, column=1) 
e8.grid(row=6, column=1)
Label(root, text='SECTION').grid(row=7) 
Label(root, text='OUT TIME').grid(row=8) 
e9 = Entry(root) 
e10 = Entry(root) 
e9.grid(row=7, column=1) 
e10.grid(row=8, column=1)
mainloop()